(()=>{
const $=id=>document.getElementById(id),PK='meridian.profile.v1',API_ROOT=location.port==='4173'?`${location.protocol}//${location.hostname}:4174/api`:'/api';window.meridianApiRoot=API_ROOT;let player=null,room=null,inviteBase=location.origin+location.pathname,entryCode=new URLSearchParams(location.search).get('room')||'',pollTimer;
try{player=JSON.parse(localStorage.getItem(PK)||'null')}catch{}
const style=document.createElement('style');style.textContent=`.playerbadge{display:flex;align-items:center;gap:7px;color:#c7ee79;font-size:11px}.playerdot{width:10px;height:10px;border-radius:50%;background:#c7ee79}.roomtag{cursor:pointer}.portal{position:fixed;inset:0;background:#0d110ecc;backdrop-filter:blur(8px);display:grid;place-items:center;padding:20px;z-index:20}.portal.hidden{display:none}.portalbox{width:min(485px,100%);background:#1a211c;border:1px solid #46523f;border-radius:16px;padding:27px;box-shadow:0 20px 90px #000a}.portalbox h2{font-size:26px;margin:6px 0}.portalbox p{font-size:13px;line-height:1.6;color:#8f9a8f}.portalinput{width:100%;background:#111612;border:1px solid #39443b;border-radius:7px;color:#f0f2e9;padding:12px;font:14px 'DM Sans',sans-serif;margin:8px 0}.portalbox .eyebrow{margin-top:12px}.portalrow{display:flex;gap:9px;align-items:center}.portalbox .btn{margin-top:10px}.roomnotice{padding:10px;background:#222b21;border-radius:7px;color:#aab4a5;font-size:11px;margin-top:13px;line-height:1.5}.roomroster{margin-top:15px;border-top:1px solid #303a31}.roomplayer{padding:10px 2px;border-bottom:1px solid #303a31;display:flex;align-items:center;justify-content:space-between;font-size:13px}.roomplayer small{color:#8f9a8f;font-size:10px}.handlepill{display:inline-block;background:#222b21;border:1px solid #384438;border-radius:10px;padding:3px 7px;margin-left:5px;color:#c7ee79!important;font:10px 'DM Mono',monospace!important}.roomactions{display:flex;gap:8px}.roomactions .btn{flex:1}.portalerror{color:#f17e68!important;min-height:18px;font-size:12px!important}.activecard{min-height:130px}.activeplayer{display:flex;align-items:center;justify-content:space-between;padding:11px 0;border-top:1px solid #283129}.activeplayername{display:flex;gap:10px;align-items:center;font-size:13px;font-weight:600}.playerinitials{width:30px;height:30px;flex:none;border-radius:50%;display:grid;place-items:center;color:#101411;font:700 11px 'DM Mono',monospace}.activeplayername small{display:block;color:#c1cabe;font:10px 'DM Mono',monospace;margin-top:3px}.activebadge{font:9px 'DM Mono',monospace;color:#c7ee79;border:1px solid #3a4a34;border-radius:12px;padding:4px 7px}.online{color:#c7ee79;font:10px 'DM Mono',monospace}@media(max-width:510px){.portalbox{padding:21px}.topright{gap:7px}.playerbadge b{max-width:70px;overflow:hidden;text-overflow:ellipsis}}`;document.head.append(style);
const portal=document.createElement('div');portal.className='portal';portal.id='portal';portal.innerHTML='<div class="portalbox" id="portalContent"></div>';document.body.append(portal);
function randomId(){return globalThis.crypto?.randomUUID?.()||('p-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10))}
function toast(msg){let t=$('toast');t.textContent=msg;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2600)}
async function api(path,method='GET',data){let r=await fetch(API_ROOT+path,{method,headers:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined,cache:'no-store'});let j=await r.json();if(!r.ok)throw Error(j.error||'Could not reach the game server');return j}
async function initialize(){window.meridianRoom=room;window.meridianPlayer=player;try{let info=await api('/info');inviteBase=info.inviteBase}catch{};if(player){player.id=player.id||randomId();localStorage.setItem(PK,JSON.stringify(player));if(entryCode){try{await joinRoom(entryCode);return}catch(e){entryCode='';renderLobbyError(e.message)}}}render()}
function renderLobbyError(msg){$('portalContent').dataset.error=msg}
function render(){let c=$('portalContent');if(player){$('playerName').textContent=player.name.toUpperCase();$('playerDot').style.background=player.color;c.innerHTML=`<div class="eyebrow">MERIDIAN · PLAYER ACCESS</div><h2>Welcome, ${escapeHtml(player.name)}.</h2><p>Join an existing room with an invite code, or create a room and share its link.</p><div class="playerbadge"><i class="playerdot" style="background:${player.color}"></i>${escapeHtml(player.name)} · @${escapeHtml(player.handle)}</div><div class="eyebrow">JOIN AN EXISTING GAME</div><div class="portalrow"><input class="portalinput" id="joinCode" maxlength="8" placeholder="Enter room code" value="${escapeHtml(entryCode)}"><button class="btn" id="joinBtn">Join →</button></div><button class="btn" id="createBtn" style="width:100%">Create a new game →</button><p class="portalerror" id="portalError">${escapeHtml(c.dataset.error||'')}</p><div class="roomnotice">Invite links and codes work across devices that can reach this computer on the same Wi-Fi network. For internet access from outside your network, the game needs online hosting.</div><button id="switchPlayer" style="background:none;border:0;color:#8f9a8f;cursor:pointer;padding:12px 0 0;font-size:11px">Switch player</button>`;c.querySelector('#joinBtn').onclick=()=>joinRoom(c.querySelector('#joinCode').value.trim().toUpperCase());c.querySelector('#createBtn').onclick=createRoom;c.querySelector('#joinCode').onkeydown=e=>{if(e.key==='Enter')joinRoom(e.target.value.trim().toUpperCase())};c.querySelector('#switchPlayer').onclick=()=>{localStorage.removeItem(PK);player=null;render()}}else{c.innerHTML=`<div class="eyebrow">MERIDIAN · PLAYER ACCESS</div><h2>Enter the arena.</h2><p>Create your player identity, then join or create a shared room.</p><div class="eyebrow">PLAYER NAME</div><input class="portalinput" id="nameInput" maxlength="18" placeholder="e.g. Field Commander"><div class="eyebrow">PLAYER HANDLE</div><input class="portalinput" id="handleInput" maxlength="16" placeholder="e.g. ORBITAL_7"><div class="eyebrow">IDENTITY COLOR</div><input class="portalinput" id="colorInput" type="color" value="#c7ee79" style="height:44px;padding:4px"><button class="btn" id="loginBtn" style="width:100%">Continue to lobby →</button>`;c.querySelector('#loginBtn').onclick=()=>{let name=c.querySelector('#nameInput').value.trim(),handle=c.querySelector('#handleInput').value.trim().replace(/^@/,'').toUpperCase();if(!name||!handle)return toast('Enter a player name and handle first.');player={id:randomId(),name,handle,color:c.querySelector('#colorInput').value};window.meridianPlayer=player;localStorage.setItem(PK,JSON.stringify(player));render();if(entryCode)joinRoom(entryCode)}}}
function escapeHtml(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function createRoom(){try{let r=await api('/rooms','POST',{player});room=r;room=await api(`/rooms/${r.code}/join`,'POST',{player});window.meridianRoom=room;window.meridianPlayer=player;showLobby()}catch(e){toast(e.message)}}
async function joinRoom(code){if(!code){toast('Enter a room code.');return}try{room=await api(`/rooms/${encodeURIComponent(code)}/join`,'POST',{player});window.meridianRoom=room;window.meridianPlayer=player;showLobby()}catch(e){let n=$('portalError');if(n)n.textContent=e.message;else toast(e.message)}}
function showLobby(){window.meridianRoom=room;window.meridianPlayer=player;entryCode=room.code;history.replaceState(null,'',location.pathname+'?room='+room.code);$('portalContent').dataset.error='';renderSharedLobby();if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(refreshLobby,3000)}
function inviteUrl(){return inviteBase+'?room='+room.code}
async function refreshLobby(){if(!room)return;try{room=await api(`/rooms/${room.code}`);if(!room.players.some(p=>p.id===player.id))room=await api(`/rooms/${room.code}/join`,'POST',{player});await api(`/rooms/${room.code}/heartbeat`,'POST',{id:player.id});window.meridianRoom=room;window.meridianPlayer=player;if(portal.classList.contains('hidden')){renderActivePlayers();window.renderRoomRoster?.();window.updateRoomScoreboard?.()}else renderSharedLobby()}catch(e){clearInterval(pollTimer);toast('Room connection lost: '+e.message)}}
function renderActivePlayers(){let c=$('activePlayers');if(!c||!room)return;let online=room.players.filter(p=>Date.now()-(p.lastSeen||0)<20000);$('activePlayerCount').textContent=`${online.length} PLAYER${online.length===1?'':'S'}`;c.innerHTML=online.length?online.map(p=>`<div class="activeplayer"><div class="activeplayername"><i class="playerinitials" style="background:${escapeHtml(p.color||'#c7ee79')}">${escapeHtml(String(p.name||'?').slice(0,2).toUpperCase())}</i><span>${escapeHtml(p.name)}<small>@${escapeHtml(p.handle||'PLAYER')}</small></span></div><span class="activebadge">${p.id===player.id?'YOU · ACTIVE':p.id===room.host?'HOST · ACTIVE':'ACTIVE'}</span></div>`).join(''):'<div class="roomnotice">No active players detected.</div>'}
function renderSharedLobby(){let c=$('portalContent');c.innerHTML=`<div class="eyebrow">SHARED GAME ROOM</div><h2>Room ${room.code}</h2><p>Invite others with this code or link. Connected players appear here.</p><div class="portalrow"><input class="portalinput" id="inviteUrl" readonly value="${escapeHtml(inviteUrl())}"><button class="btn" id="copyInvite">Copy link</button></div><div class="portalrow"><span class="pill">INVITE CODE</span><strong style="font:20px 'DM Mono',monospace;color:#c7ee79;letter-spacing:.13em">${room.code}</strong><span class="online">● LIVE</span></div><div class="roomroster">${room.players.map(p=>`<div class="roomplayer"><span><i class="playerdot" style="display:inline-block;vertical-align:middle;margin-right:8px;background:${escapeHtml(p.color||'#c7ee79')}"></i>${escapeHtml(p.name)} <small class="handlepill">@${escapeHtml(p.handle||'PLAYER')}</small></span><small>${p.id===room.host?'HOST':'JOINED'}</small></div>`).join('')}</div><div class="roomnotice">Room members compete by submitting allocations. Standings update as active players lock in, then finalize for everyone in the room.</div><div class="roomactions"><button class="btn" id="startBtn">Enter arena →</button><button class="btn" id="backBtn" style="background:#384234;color:#f0f2e9;box-shadow:none">Leave room</button></div>`;c.querySelector('#copyInvite').onclick=()=>navigator.clipboard?.writeText(inviteUrl()).then(()=>toast('Invite link copied')).catch(()=>{c.querySelector('#inviteUrl').select();document.execCommand('copy');toast('Invite link copied')});c.querySelector('#startBtn').onclick=()=>{portal.classList.add('hidden');renderActivePlayers();$('roomTag').textContent='ROOM '+room.code;$('roomTag').title='Invite code: '+room.code+' · Click to copy link';$('roomTag').onclick=()=>{navigator.clipboard?.writeText(inviteUrl()).then(()=>toast('Invite link copied')).catch(()=>prompt('Copy invite link',inviteUrl()))};if(typeof reset==='function')reset()};c.querySelector('#backBtn').onclick=()=>{clearInterval(pollTimer);room=null;history.replaceState(null,'',location.pathname);render()}}
initialize();
})();




