const http=require('http'),fs=require('fs'),path=require('path'),os=require('os');
const root=__dirname,port=Number(process.env.PORT)||4173,rooms=new Map();
function lanAddress(){for(const list of Object.values(os.networkInterfaces()))for(const x of list||[])if(x.family==='IPv4'&&!x.internal&&/^192\.168\.|^10\.|^172\.(1[6-9]|2\d|3[01])\./.test(x.address))return x.address;return '127.0.0.1'}
function send(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Cache-Control':'no-store'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',d=>b+=d);req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}})})}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost');if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type'});return res.end()}
if(u.pathname==='/api/health')return send(res,200,{ok:true});
if(u.pathname==='/api/info'){const proto=req.headers['x-forwarded-proto']||'http',host=req.headers.host||`${lanAddress()}:${port}`;return send(res,200,{host,port,inviteBase:`${proto}://${host}/`})}
if(u.pathname==='/api/rooms'&&req.method==='POST'){let b=await body(req),code;do{code=Math.random().toString(36).slice(2,8).toUpperCase()}while(rooms.has(code));let room={code,host:(b.player?.id||b.player?.handle),players:[],submissions:{},tier:1,tierWins:0,resolvedRounds:{},created:Date.now()};rooms.set(code,room);return send(res,201,room)}
let m=u.pathname.match(/^\/api\/rooms\/([A-Z0-9]+)(?:\/(join|heartbeat|submit))?$/i);if(m){let code=m[1].toUpperCase(),action=m[2],room=rooms.get(code);if(!room)return send(res,404,{error:'Room not found. Check the code or ask the host to create a new room.'});if(req.method==='POST'&&action==='join'){let b=await body(req),id=String(b.player?.id||'');if(!id)return send(res,400,{error:'Player identity required'});let p=room.players.find(x=>x.id===id);if(p)Object.assign(p,b.player,{lastSeen:Date.now()});else room.players.push({...b.player,lastSeen:Date.now()});return send(res,200,room)}if(req.method==='POST'&&action==='heartbeat'){let b=await body(req),p=room.players.find(x=>x.id===b.id);if(p)p.lastSeen=Date.now();room.players=room.players.filter(x=>Date.now()-x.lastSeen<20000);return send(res,200,room)}if(req.method==='POST'&&action==='submit'){let b=await body(req),p=room.players.find(x=>x.id===b.id);if(!p)return send(res,403,{error:'Join this room before submitting a score'});let key=String(b.roundKey||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,32);if(!key||!Number.isFinite(Number(b.score)))return send(res,400,{error:'A valid round and score are required'});room.submissions=room.submissions||{};room.submissions[key]=room.submissions[key]||{};room.submissions[key][p.id]={id:p.id,name:p.name,handle:p.handle,color:p.color,score:Number(b.score),submittedAt:Date.now()};p.lastSeen=Date.now();room.tier=room.tier||1;room.tierWins=room.tierWins||0;room.resolvedRounds=room.resolvedRounds||{};let active=room.players.filter(x=>Date.now()-x.lastSeen<20000),roundScores=room.submissions[key]||{};if(active.length&&active.every(x=>roundScores[x.id])&&!room.resolvedRounds[key]){room.resolvedRounds[key]=true;room.tierWins++;if(room.tierWins>=3){room.tier++;room.tierWins=0}}return send(res,200,room)}if(req.method==='GET'){room.players=room.players.filter(x=>Date.now()-x.lastSeen<20000);return send(res,200,room)}return send(res,405,{error:'Method not allowed'})}
let file=path.join(root,decodeURIComponent(u.pathname));if(!file.startsWith(root)){res.writeHead(403);return res.end('Forbidden')}if(u.pathname==='/')file=path.join(root,'index.html');fs.readFile(file,(e,data)=>{if(e){res.writeHead(404);return res.end('Not found')}let ext=path.extname(file);res.writeHead(200,{'Content-Type':ext==='.html'?'text/html; charset=utf-8':ext==='.js'?'text/javascript; charset=utf-8':'application/octet-stream','Cache-Control':'no-store'});res.end(data)})
});server.listen(port,'0.0.0.0',()=>console.log(`Meridian running on http://${lanAddress()}:${port} (LAN)`));

